<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>评分系统单点登录</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <!-- Font Awesome Icons -->
    <!--<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />-->
    <!-- Theme style -->
    <link href="/css/AdminLTE.min.css" rel="stylesheet" type="text/css"/>
    <!-- iCheck -->
    <link href="/css/blue.css" rel="stylesheet" type="text/css"/>
    
    <!-- Bootstrap 3.3.2 JS -->
    <script src="/js/bootstrap.min.js" type="text/javascript"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
<!--    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>-->
    <!--<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>-->
    <!--[endif]-->
</head>
<body class="login-page">
<div class="login-box">
    <div class="login-logo">
        <b>评分系统单点登录</b>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body" style="position: relative;">
        <p class="login-box-msg">Hi,欢迎来到评分系统，请填写登录信息</p>

        <form method="post">
            <div class="form-group has-feedback">
                <input type="text" name="userId" class="form-control info" placeholder="学号/工号"
                       required="" style="width:320px;"/>
                <span class="glyphicon glyphicon-star form-control-feedback"></span>
            </div>

            <div class="form-group has-feedback">
                <input type="password" name="password" class="form-control pass" placeholder="请输入密码"
                       required="" style="width:320px;"/>
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <br>
            <div>
                <button type="submit" class="btn btn-primary btn-block btn-flat"><b>登&nbsp;&nbsp录</b>
                </button>
            </div>
            <br>
        </form>
    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->
</body>
</html>