<meta charset="utf-8">
<form method="post">
    <input type="url" name="redirect_uri" value="http://" placeholder="redirect_uri" required="">
    <input type="text" name="client_name" placeholder="公司名称" required="">
    <input type="text" name="client_logo_url" placeholder="公司logo(填url)" required="">
    <input type="text" name="client_homepage" placeholder="公司主页" required="">
    <input type="submit" value="注册">
</form>